# This docker compose for developing image tunnel

services:
  sshd_tunnel:
    container_name: sshd_tunnel
    restart: unless-stopped
    environment:
      PRIVATE_MODE_TOKEN: mplusjayaselalu
    build:
      context: .
      dockerfile: ./tunnel.Dockerfile
    ports:
      - 2222:22
