name: Build Image for all Dockerfile

on:
  push:
    branches:
      - master

jobs:
  build-sshd:
    uses: ./.github/workflows/build-push.yml
    with:
      folder_path: .
      images_name: ghcr.io/${{ github.repository }}-sshd-tunnel
    secrets: inherit
