name: Test build & Upload staging binaries to M+ S3

on:
  push:
    branches:
      - master

jobs:
  # For testing
  test-build:
    strategy:
      matrix:
        make_command: [build-client, build-tunnel]
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: ${{ matrix.make_command }}
    secrets: inherit

  artifact-build:
    needs: [test-build]
    strategy:
      matrix:
        make_command: [build-client, build-tunnel]
        include:
          - make_command: build-client
            binary_name: mdrop
          - make_command: build-tunnel
            binary_name: mdrop-tunnel
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: ${{ matrix.make_command }}
      use_artifacts: true
      binary_name: ${{ matrix.binary_name }}
    secrets: inherit

  artifact-upload:
    needs: [artifact-build]
    strategy:
      matrix:
        binary_name: [mdrop, mdrop-tunnel]
    uses: ./.github/workflows/reusable-upload-s3.yml
    with:
      binary_name: ${{ matrix.binary_name }}
    secrets: inherit
