name: Build Image for all Dockerfile

on:
  push:
    branches:
      - master

jobs:
  build-broker:
    uses: ./.github/workflows/build-push.yml
    with:
      folder_path: server/
    secrets: inherit

  build-sshd:
    uses: ./.github/workflows/build-push.yml
    with:
      folder_path: tunnel_image/
      images_name: ghcr.io/${{ github.repository }}-sshd-tunnel
    secrets: inherit
