name: Test build & Upload staging binaries to M+ S3

on:
  push:
    branches:
      - github/darwin-macos

jobs:
  test-build:
    runs-on: macos-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Build
        run: make build-client-darwin
      - name: Check file
        run: ls -lah
