name: Test build & Upload staging binaries to M+ S3

on:
  push:
    branches:
      - github/darwin-macos

jobs:
  test-build:
    strategy:
      matrix:
        make_command: [build-client-darwin, build-tunnel-darwin]
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: ${{ matrix.make_command }}
      runner: macos-latest
      binary_name: mdrop-darwin
    secrets: inherit
