name: Build Image for SSHD Tunnel

on:
  push:
    branches:
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.mitija.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Generate Docker image metadata
        uses: docker/metadata-action@v5
        id: img_meta
        with:
          flavor: |
            latest=auto
            suffix=${{ steps.flavor.outputs.name }}
          images: registry.mitija.com/${{ github.repository }}-sshd-tunnel
          tags: |
            type=sha,format=short,prefix=commit-
            type=raw,value=latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: tunnel_image/
          push: true
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
