name: Test build & Upload staging binaries to M+ S3

on:
  push:
    branches:
      - github/darwin-macos

jobs:
  build:
    runs-on: macos-latest
    container:
      image: docker.io/library/golang:alpine
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        if: ${{ inputs.runner != 'ubuntu-latest' }}
        with:
          go-version: 1.22
      - name: Build app
        run: make build-client-general
