name: Test build & Upload staging binaries to M+ S3

on:
  push:
    branches:
      - master

jobs:
  # For testing
  test-build:
    strategy:
      matrix:
        make_command: [build-client, build-tunnel]
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: ${{ matrix.make_command }}
    secrets: inherit

  artifact-build:
    needs: [test-build]
    strategy:
      matrix:
        make_command: [build-client]
        include:
          - make_command: build-client
            binary_name: mdrop
            binary_os: linux
            binary_arch: amd64
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: ${{ matrix.make_command }}
      use_artifacts: true
      binary_name: ${{ matrix.binary_name }}
      binary_os: ${{ matrix.binary_os }}
      binary_arch: ${{ matrix.binary_arch }}
    secrets: inherit

  artifact-upload:
    needs: [artifact-build]
    strategy:
      matrix:
        binary_name: [mdrop]
        include:
          - binary_name: mdrop
            binary_os: linux
            binary_arch: amd64
    uses: ./.github/workflows/reusable-upload-s3.yml
    with:
      binary_name: ${{ matrix.binary_name }}
      binary_os: ${{ matrix.binary_os }}
      binary_arch: ${{ matrix.binary_arch }}
    secrets: inherit
