name: Upload file to S3

on:
  push:
    branches:
      - master
      - development

jobs:
  client:
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: build-client
      use_artifacts: true
      binary_name: mdrop
    secrets: inherit

  client-upload:
    needs: client
    uses: ./.github/workflows/reusable-upload-s3.yml
    with:
      binary_name: mdrop
    secrets: inherit

  tunnel:
    uses: ./.github/workflows/reusable-build-golang-alpine.yml
    with:
      make_command: build-tunnel
      use_artifacts: true
      binary_name: mdrop-tunnel
    secrets: inherit

  tunnel-upload:
    needs: tunnel
    uses: ./.github/workflows/reusable-upload-s3.yml
    with:
      binary_name: mdrop-tunnel
    secrets: inherit
