name: Build Image for all Dockerfile

on:
  push:
    branches:
      - master
      - development

jobs:
  build-sshd:
    uses: ./.github/workflows/reusable-push-image.yml
    with:
      context: .
      file: tunnel.Dockerfile
      images_name: ghcr.io/${{ github.repository }}-sshd-tunnel
    secrets: inherit
