name: Reusable workflow for upload file to S3

on:
  workflow_call:
    secrets:
      BUCKET_URL:
        required: true
      BUCKET_USERNAME:
        required: true
      BUCKET_PASSWORD:
        required: true
      BUCKET_NAME:
        required: true
    inputs:
      binary_name:
        type: string
        default: mdrop
      binary_os:
        type: string
        default: linux
      binary_arch:
        type: string
        default: amd64

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.binary_name }}-${{ inputs.binary_os }}-${{ inputs.binary_arch }}-artifact
      - name: Check file
        run: |
          pwd
          ls -lah
      - name: Install curl + openssl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl openssl
      - name: Upload file
        uses: shallwefootball/upload-s3-action@master
        with:
          endpoint: ${{ secrets.BUCKET_URL }}
          aws_key_id: ${{ secrets.BUCKET_USERNAME }}
          aws_secret_access_key: ${{ secrets.BUCKET_PASSWORD }}
          aws_bucket: ${{ secrets.BUCKET_NAME }}
          source_dir: .
          destination_dir: .
