name: Reusable workflow for build golang on alpine

on:
  workflow_call:
    inputs:
      make_command:
        type: string
        default: restore
      use_artifacts:
        type: boolean
        default: false
      binary_name:
        type: string
        default: mdrop

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/golang:alpine
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install cgo + make Dependencies
        run: |
          apk update
          apk add make gcc musl-dev
      - name: Build app
        run: make ${{ inputs.make_command }}
      - name: Upload artifacts
        if: ${{ inputs.use_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.binary_name }}-build-artifact
          path: ${{ inputs.binary_name }}
